version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building application"
      - zip -r app.zip . -x node_modules/\* .git/\*
artifacts:
  files:
    - app.zip
  discard-paths: yes
